repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 23.7.0 # Sử dụng phiên bản mới nhất tại thời điểm bạn cài đặt
    hooks:
      - id: black
        language_version: python3.12.1 # Điều chỉnh theo phiên bản Python của bạn
